#!/usr/bin/env python
import networkx as nx
import operator

def usa():
    G=nx.Graph()

    #Region Purple
    G.add_node("Seattle", region="purple")
    G.add_node("Portland", region="purple")
    G.add_node("Boise", region="purple")
    G.add_node("Billings", region="purple")
    G.add_node("Cheyenne", region="purple")
    G.add_node("Denver", region="purple")
    G.add_node("Omaha", region="purple")

    #Region Teal
    G.add_node("San Francisco", region="teal")
    G.add_node("Los Angeles", region="teal")
    G.add_node("San Diego", region="teal")
    G.add_node("Las Vegas", region="teal")
    G.add_node("Phoenix", region="teal")
    G.add_node("Salt Lake City", region="teal")
    G.add_node("Santa Fe", region="teal")

    #Region Red
    G.add_node("Kansas City", region="red")
    G.add_node("Oklahoma City", region="red")
    G.add_node("Dallas", region="red")
    G.add_node("Houston", region="red")
    G.add_node("New Orleans", region="red")
    G.add_node("Memphis", region="red")
    G.add_node("Birmingham", region="red")

    #Region Green
    G.add_node("Atlanta", region="green")
    G.add_node("Raleigh", region="green")
    G.add_node("Norfolk", region="green")
    G.add_node("Savannah", region="green")
    G.add_node("Jacksonville", region="green")
    G.add_node("Tampa", region="green")
    G.add_node("Miami", region="green")

    #Region Yellow
    G.add_node("Fargo", region="yellow")
    G.add_node("Duluth", region="yellow")
    G.add_node("Minneapolis", region="yellow")
    G.add_node("Chicago", region="yellow")
    G.add_node("St. Louis", region="yellow")
    G.add_node("Cincinnati", region="yellow")
    G.add_node("Knoxville", region="yellow")

    #Region Brown
    G.add_node("Detroit", region="brown")
    G.add_node("Pittsburgh", region="brown")
    G.add_node("Washington D.C.", region="brown")
    G.add_node("Philadelphia", region="brown")
    G.add_node("New York", region="brown")
    G.add_node("Boston", region="brown")
    G.add_node("Buffalo", region="brown")

    G.add_edge("Seattle", "Portland", weight=3 )
    G.add_edge("Seattle", "Boise", weight=12 )
    G.add_edge("Seattle", "Billings", weight=9 )
    G.add_edge("Portland", "Billings", weight=13 )
    G.add_edge("Portland", "San Francisco", weight=24 )
    G.add_edge("Boise", "San Francisco", weight=23 )
    G.add_edge("Boise", "Billings", weight=12 )
    G.add_edge("Boise", "Cheyenne", weight=24 )
    G.add_edge("Boise", "Salt Lake City", weight=8 )
    G.add_edge("Billings", "Fargo", weight=17 )
    G.add_edge("Billings", "Minneapolis", weight=17 )
    G.add_edge("Billings", "Cheyenne", weight=9 )
    G.add_edge("Cheyenne", "Denver", weight=0 )
    G.add_edge("Cheyenne", "Omaha", weight=14 )
    G.add_edge("Cheyenne", "Minneapolis", weight=18 )
    G.add_edge("Denver", "Salt Lake City", weight=21 )
    G.add_edge("Denver", "Kansas City", weight=16 )
    G.add_edge("Denver", "Santa Fe", weight=13 )
    G.add_edge("Omaha", "Kansas City", weight=5 )
    G.add_edge("Omaha", "Minneapolis", weight=8 )
    G.add_edge("Omaha", "Chicago", weight=13 )


    G.add_edge("San Francisco", "Las Vegas", weight=14 )
    G.add_edge("San Francisco", "Salt Lake City", weight=27 )
    G.add_edge("San Francisco", "Los Angeles", weight=9 )
    G.add_edge("Los Angeles", "Las Vegas", weight=9 )
    G.add_edge("Los Angeles", "San Diego", weight=3 )
    G.add_edge("San Diego", "Las Vegas", weight=9 )
    G.add_edge("San Diego", "Phoenix", weight=14 )
    G.add_edge("Las Vegas", "Salt Lake City", weight=18 )
    G.add_edge("Las Vegas", "Santa Fe", weight=27 )
    G.add_edge("Las Vegas", "Phoenix", weight=15 )
    G.add_edge("Phoenix", "Santa Fe", weight=18 )
    G.add_edge("Salt Lake City", "Santa Fe", weight=28 )
    G.add_edge("Santa Fe", "Kansas City", weight=16 )
    G.add_edge("Santa Fe", "Oklahoma City", weight=15 )
    G.add_edge("Santa Fe", "Dallas", weight=15 )
    G.add_edge("Santa Fe", "Houston", weight=21 )


    G.add_edge("Kansas City", "Chicago", weight=8 )
    G.add_edge("Kansas City", "St. Louis", weight=6 )
    G.add_edge("Kansas City", "Memphis", weight=12 )
    G.add_edge("Kansas City", "Oklahoma City", weight=8 )
    G.add_edge("Oklahoma City", "Dallas", weight=3 )
    G.add_edge("Oklahoma City", "Memphis", weight=14 )
    G.add_edge("Dallas", "Memphis", weight=12 )
    G.add_edge("Dallas", "New Orleans", weight=12 )
    G.add_edge("Dallas", "Houston", weight=5 )
    G.add_edge("Houston", "New Orleans", weight=8 )
    G.add_edge("New Orleans", "Memphis", weight=7 )
    G.add_edge("New Orleans", "Birmingham", weight=11 )
    G.add_edge("New Orleans", "Jacksonville", weight=16 )
    G.add_edge("Memphis", "St. Louis", weight=7 )
    G.add_edge("Memphis", "Birmingham", weight=6 )
    G.add_edge("Birmingham", "Atlanta", weight=3 )
    G.add_edge("Birmingham", "Jacksonville", weight=9 )


    G.add_edge("Fargo", "Duluth", weight=6 )
    G.add_edge("Fargo", "Minneapolis", weight=6 )
    G.add_edge("Duluth", "Minneapolis", weight=5 )
    G.add_edge("Duluth", "Detroit", weight=15 )
    G.add_edge("Duluth", "Chicago", weight=12 )
    G.add_edge("Minneapolis", "Chicago", weight=8 )
    G.add_edge("Chicago", "St. Louis", weight=10 )
    G.add_edge("Chicago", "Cincinnati", weight=7 )
    G.add_edge("Chicago", "Detroit", weight=7 )
    G.add_edge("Cincinnati", "Knoxville", weight=6 )
    G.add_edge("Cincinnati", "St. Louis", weight=12 )
    G.add_edge("Cincinnati", "Detroit", weight=4 )
    G.add_edge("Cincinnati", "Raleigh", weight=15 )
    G.add_edge("Cincinnati", "Pittsburgh", weight=7 )
    G.add_edge("St. Louis", "Atlanta", weight=12 )


    G.add_edge("Detroit", "Pittsburgh", weight=6 )
    G.add_edge("Detroit", "Buffalo", weight=7 )
    G.add_edge("Pittsburgh", "Buffalo", weight=7 )
    G.add_edge("Pittsburgh", "Washington D.C.", weight=6 )
    G.add_edge("Pittsburgh", "Raleigh", weight=7 )
    G.add_edge("Buffalo", "New York", weight=8 )
    G.add_edge("New York", "Boston", weight=3 )
    G.add_edge("New York", "Philadelphia", weight=0 )
    G.add_edge("Philadelphia", "Washington D.C.", weight=3 )
    G.add_edge("Washington D.C.", "Norfolk", weight=5 )
    G.add_edge("Norfolk", "Raleigh", weight=3 )


    G.add_edge("Norfolk", "Raleigh", weight=3 )
    G.add_edge("Raleigh", "Savannah", weight=7 )
    G.add_edge("Raleigh", "Atlanta", weight=7 )
    G.add_edge("Atlanta", "Savannah", weight=7 )
    G.add_edge("Savannah", "Jacksonville", weight=0 )
    G.add_edge("Jacksonville", "Tampa", weight=4 )
    G.add_edge("Tampa", "Miami", weight=4 )
    return G

